Issue #SB-28061 - Merge user course job
Sunbird-Lern/data-pipeline pull request #5
Opened 2022-06-20 03:04 UTC by pritha-tarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-21 10:21 UTC, prasadmoka commented on lms-jobs/merge-user-courses/pom.xml
> +    <artifactId>knowledge-platform-jobs</artifactId>
it should be lern-pipeline-jobs instead of knowledge-platform-jobs

2022-06-22 05:58 UTC, prasadmoka commented on lms-jobs/merge-user-courses/src/main/scala/org/sunbird/job/merge/user/courses/functions/MergeUserCourseFunction.scala
> +        e.printStackTrace()
Remove stacktrace and if required add it to the log file

2022-06-22 05:59 UTC, prasadmoka commented on lms-jobs/merge-user-courses/src/main/scala/org/sunbird/job/merge/user/courses/util/MergeOperations.scala
> +    System.out.println("batchIdsToBeMigrated =>"+batchIdsToBeMigrated)
Use logger statement instead of sysouts

2022-06-22 06:03 UTC, prasadmoka commented on lms-jobs/merge-user-courses/src/test/scala/org/sunbird/job/merge/user/courses/spec/MergeUserCourseFuncTest.scala
> +    System.out.print("====starting res====")
remove sysout

2022-06-22 06:03 UTC, prasadmoka commented on lms-jobs/merge-user-courses/src/test/scala/org/sunbird/job/merge/user/courses/spec/MergeUserCourseFuncTest.scala
> +    System.out.print("====Ending res====")
remove sysout

2022-06-22 09:25 UTC, prasadmoka requested changes
Make necessary changes

2022-06-30 07:39 UTC, pritha-tarento commented
PR is having lot of files that were not required, so closing

2022-06-30 07:39 UTC, closed without merging